CREATE DATABASE AMAZON;
USE AMAZON;
/* TASK 3 #
Inner Join for Order Details :
Join orders, order_items, and products to display detailed line items? */
SELECT*
FROM ORDERS AS O
JOIN ORDER_ITEMS AS OT
ON O.ORDER_ID=OT.ORDER_ID
JOIN PRODUCTS AS P
ON OT.PRODUCT_ID=P.PRODUCT_ID;

drop table order_items;

/* TASK 4 #
Total Sales by Store :
Write a query to group sales (total_price) by each store_id? */
SELECT S.STORE_ID,S.STORE_NAME, ROUND(SUM(OT.TOTAL_SALES)) AS TOTAL_SALES
FROM ORDER_ITEMS AS OT
JOIN ORDERS AS O
ON OT.ORDER_ID=O.ORDER_ID
JOIN STORES AS S
ON O.STORE_ID=S.STORE_ID
GROUP BY S.STORE_ID,S.STORE_NAME;

/* TASK 5 #
Top 5 Selling Products 
Use ORDER BY and LIMIT to get the top 5 most sold products by quantity? */
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,COUNT(OT.QUANTITY) AS TOTAL_QUANTITY
FROM ORDER_ITEMS AS OT
JOIN PRODUCTS AS P
ON OT.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME,P.PRODUCT_ID
ORDER BY TOTAL_QUANTITY DESC
LIMIT 5;

/* TASK 6 #
Customer Purchase Summary 
For each customer, return total orders placed, total items purchased, and total revenue? */
SELECT C.CUSTOMER_ID AS CUSTOMER,
	   COUNT(OT.ORDER_ID) AS TOTAL_ORDERS, 
       COUNT(OT.ITEM_ID) AS TOTAL_ITEMS, 
       ROUND(SUM(OT.TOTAL_SALES)) AS TOTAL_SALES
FROM CUSTOMERS AS C
JOIN ORDERS AS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN ORDER_ITEMS AS OT
ON O.ORDER_ID=OT.ORDER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY TOTAL_SALES DESC;

/* TASK 7 #
Segment Customers by Total Spend 
Write a query to classify customers into spending brackets (e.g., low, 
medium, high)? */
SELECT C.CUSTOMER_ID AS CUSTOMER_ID,
	   C.FIRST_NAME AS NAME,
       ROUND(SUM(OT.TOTAL_SALES)) AS TOTAL_SALES,
       CASE
        WHEN SUM(OT.total_sales) < 1000 THEN 'Low'
        WHEN SUM(OT.total_sales) BETWEEN 1000 AND 10000 THEN 'Medium'
        ELSE 'High'
    END AS spend_category
FROM CUSTOMERS AS C
JOIN ORDERS AS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN ORDER_ITEMS AS OT
ON O.ORDER_ID=OT.ORDER_ID
GROUP BY C.CUSTOMER_ID,C.FIRST_NAME
ORDER BY TOTAL_SALES DESC;

/* TASK 8 #
Staff Performance Analysis 
Analyze total revenue generated by each staff member based on their 
handled orders? */
SELECT S.STAFF_ID AS STAFF_ID, 
       CONCAT(S.FIRST_NAME," ",S.LAST_NAME) AS NAME,
	   ROUND(SUM(OT.TOTAL_SALES)) AS TOTAL_REVENUE
FROM ORDER_ITEMS AS OT
JOIN ORDERS AS O
ON O.ORDER_ID=OT.ORDER_ID
JOIN STAFFS AS S
ON O.STAFF_ID=S.STAFF_ID
GROUP BY S.STAFF_ID, NAME
ORDER BY TOTAL_REVENUE DESC;

/* TASK 9 # 
Stock Alert Query 
Write a query to list products where stock quantity < 10 in any store? */
SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(S.QUANTITY) AS TOTAL_QUANTITY
FROM STOCKS AS S
JOIN PRODUCTS AS P
ON S.PRODUCT_ID=P.PRODUCT_ID
WHERE S.QUANTITY<10
GROUP BY P.PRODUCT_NAME,P.PRODUCT_ID
HAVING sum(S.QUANTITY)<10;

/* Task 10 #
Create Final Segmentation Table 
Create a table customer_segments that will be populated from Python ML results later? */
CREATE TABLE customer_segments 
    (customer_id INT PRIMARY KEY,
    segment_label VARCHAR(50),
    score DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);